version: 0.2
phases: 
  install:
    commands:
      # install terraform binary
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  pre_build:
    commands:
     - cd ecr
     - terraform init
     - terraform plan
     - terraform apply -auto-approve
  build:
    commands:
     - cd ..
     - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 870597747842.dkr.ecr.us-east-1.amazonaws.com
     - docker build -t djangoapp .
     - docker tag djangoapp:latest 870597747842.dkr.ecr.us-east-1.amazonaws.com/djangoapp:latest
     - docker push 870597747842.dkr.ecr.us-east-1.amazonaws.com/djangoapp:latest
  post_build:
    commands:
     - cd ecs
     - terraform init
     - terraform plan
     - terraform apply -auto-approve
# test Commit
